biddu/biddu/urls.py
from django.contrib import admin
from django.urls import path,include

# password:pass


app_name = 'app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

biddu/main/urls.py
from django.urls import path
from . import views

app_name = 'userapp'
urlpatterns = [
   
    path('',views.index,name = 'index'),
    path('register/', views.register_page,name='register'),
    path('login/', views.login_page,name='login'),
    path('login/', views.logout_page,name='logout'),
    path('main/contact/', views.contact,name='contact'),
    path('searchList/',views.searchList,name='searchList')
    
]

biddu/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls.base import reverse

# Create your models here.
class UserInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    git_url=models.URLField(blank=True)
    profile_pic=models.ImageField(blank=True,upload_to='profile_image')


    def _str_(self):
        return self.user.username

class Contact(models.Model):
    msg_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=70, default="")
    phone = models.CharField(max_length=70, default="")
    desc = models.CharField(max_length=500, default="")

    def __str__(self):
        return self.name


class Hostel(models.Model):
    hostel_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200,default="")
    type = models.CharField(max_length=50)
    budget = models.IntegerField(default=0)
    gender = models.CharField(max_length=50)

    def __str__(self):
        return self.name

biddu/main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.db.models import fields
from .models import UserInfo

class UserForm(forms.ModelForm):
    password= forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model=User
        fields=('username','email','password')
class UserInfoForm(forms.ModelForm):
    class Meta:
        model=UserInfo
        fields=('git_url','profile_pic')
class LoginForm(forms.Form):
    username=forms.CharField(max_length=150,label='Your Name:')
    password=forms.CharField(widget=forms.PasswordInput())

biddu/main/views.py
from cgitb import Hook
from django.shortcuts import render
from django.http import HttpResponse
from django.db import models
from django.db.models import fields
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic.base import View
from .forms import LoginForm, UserForm, UserInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
# Create your views here.
from django.views.generic import(View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView)
from . import models
from .models import Contact, Hostel

def index(response):
     return render(response, 'main/index.html')

# Register and Login Page
def register_page(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        user_info_form = UserInfoForm(request.POST)
        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_info = user_info_form.save(commit=False)

            user_info.user = user

            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']
            user_info.save()
            registered = True
        else:
            print(user_form.errors, user_info_form.errors)

    else:
        user_form = UserForm()
        user_info_form = UserInfoForm()

    return render(request, 'main/register.html', {'user_form':user_form, 'user_info_form':user_info_form, 'registered':registered})


def login_page(request):
    login_error = ''
    login_form = LoginForm()
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:  # login credentials matched
            if user.is_active:
                login(request, user)  # login successful
                return redirect(reverse('userapp:home'))
            else:
                return HttpResponse('Acount is not active')
        else:
            login_error = 'Invalid Login Details'

    return render(request, 'main/login.html', {'login_error': login_error, 'login_form': login_form})


@login_required
def home_page(request):
    return render(request, 'main/basic.html')


@login_required
def logout_page(request):
    logout(request)
    return redirect(reverse('userapp:index'))

def contact(request):
    thank=False
    if request.method == "POST":
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        desc = request.POST.get('desc', '')
        print(request)
        contact = Contact(name=name, email=email, phone=phone, desc=desc)
        contact.save()
        thank=True
    return render(request, 'main/contact.html',{'thank':thank})  


def searchList(response):

    allHostels = []
    allHostels= Hostel.objects.values_list
    
    params = {'allHostels': allHostels}
    print(params)
    return render(response, 'main/searchList.html', params)   
    

biddu/main/templates/main/basic.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'index.css' %}"> 
    <link rel="stylesheet" href="{%static 'searchList.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
                    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
        
    <title>{% block title %}{% endblock %}</title>

  </head>
  
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="mx-3 navbar-brand" href="#">Biddu</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link mx-5" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-5" href="#">WatchList</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled mx-5" href="#">My Favorite</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled mx-5" href="#">Memes</a>
        </li>

        <li class="nav-item">
          <a class="nav-link mx-5" href="#">Help</a>
        </li>
        <li class="nav-item log" >
          <a class="nav-link" href="{% url 'userapp:login' %}">Log-In</a>
        </li>
        <li class="nav-item sign">
          <a class="nav-link" href="{% url 'userapp:register' %}">Sign-Up</a>
        </li>
        
      </ul>

    </div>
  
  </nav>
 
  {% block body %}{% endblock %}
  
  
  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>

  {% block js %} 
    <script></script>
  {% endblock %}    
  </body>
</html>

biddu/main/templates/main/contact.html
{% extends 'main/basic.html' %}
{% block body %}
<body>
    <div class="container my-3">
        <h3>Contact Us - Biddu</h3>
        <form action="/main/contact/" method="post">{% csrf_token %}
      <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" id="name" name='name' placeholder="Enter Your Name">
      </div>
      <div class="form-group">
        <label for="name">Email</label>
        <input type="email" class="form-control" id="email" name='email' placeholder="Enter Your Email">
      </div>
    
        <div class="form-group">
        <label for="name">Phone</label>
        <input type="tel" class="form-control" id="phone" name='phone' placeholder="Enter Your Phone Number">
      </div>
    
    
       <div class="form-group">
        <label for="desc">How May We Help You?</label>
        <textarea class="form-control" id="desc" name='desc' rows="3"></textarea>
       </div>
            <button type="submit" class="btn btn-success">Submit</button>
    </form>
    
    
    
    </div>
</body>
{% endblock %}

{% block js%}
<!-- <script>
  {% if thank %}
         alert('Thanks for contacting with us. We will get back to you soon!'); -->
        //  window.location = '';
        // document.location = "main/";
         
  <!-- {% endif %}        -->

{% endblock %}

  

biddu/main/templates/main/index.html
{% extends 'main/basic.html' %}

{% load static %}

<title>{% block title %}Biddu{% endblock %}</title>

{% block body %}


 <form action="searchList/" method="post" class="form">{% csrf_token %}   
  <div class="search">
 
  <input class="destination size" type="text" placeholder="Search City.." name="search">
  
  <select class ="type_of_residency size" id="type_of_residency" name="type_of_residency">
    <option value="#" style="background-color: #e9e9e9;">Type of Residency</option>
    <option value="rent" class="drop-down-option">Rent</option>
    <option value="room" class="drop-down-option">Room</option>
    <option value="flat" class="drop-down-option">Flat</option>
    <option value="pg" class="drop-down-option">PG</option>
  </select>


  <select class ="size type_of_room" id="type_of_room" name="type_of_room">
    <option style="background-color: #e9e9e9;"value="#">Type of Room</option>
    <option value="rent" class="drop-down-option">Single Room</option>
    <option value="room" class="drop-down-option">Double Room</option>
    <option value="flat" class="drop-down-option">BHK</option>
  </select>

  
    <span class="price-range">
    <label for="vol">Select Budget:</label>
    <input type="range" id="vol" name="vol" min="0" max="100000">
    </span>

    <select class ="size gender" id="gender" name="gender">
      <option style="background-color: #e9e9e9;" value="#">For: </option>
      <option value="boys" class="drop-down-option">Boys</option>
      <option value="girls" class="drop-down-option">Girls</option>
      <option value="common" class="drop-down-option">Common</option>
    </select>

    <button class="search_btn" type="submit"><i class="fa fa-search">Search</i></button>
    </div>
 
</form>

{% block content %} {% endblock %}
<section class="about">
    <h3>About Book My PG</h3>
  <div class="visible">
    <p>
      Hi Student i'm your biddu ;) (biddu means friend) 
          i'm here to help you to find your essential needs like rental rooms/pg's/mess etc.
          In a location which gonna be selected by you.
          You just tell me your needs and i will show you best results accordingly.
    </p>
  </div>
  <div class="more">Read More</div>
  <div class="hidden" style="display: none;">
      Get to know us

          How Biddu comes from thought to the physical world ;

          “Necessity is the mother of invention”
          Similarly when we moved to a completely new city, there were a lot of things which seemed to be a very difficult task. If you are a student then these difficulties are doubled.

          And one of these tasks is to find suitable and affordable accommodation.

          Just think about the process of finding a room/PG/rented flat walking hours for 2-3 days without any direction,roaming in streets searching “TO LET” hoardings on gates and after checking 30-35 rooms you find a room.

          Now think of a channel which connects you to the PGs and rooms;
          - according to your needs,
          -in your selected area,
          -within your budget,
          -without any physical work.

          Now which way would you prefer?
          Of Course the second wala…… 


          So, @biddu.com we provide that channel to you..
          Our mission is to cut off the tiredy task of finding you rooms from ground to phones and PCs .

          NOW shift to new place TENSION FREE.
    </div>
  
</section>

<section class="services">
  <h1>Our Services</h1>
  <div class="carousel"
        data-flickity='{ "wrapAround": true }'>
        <div class="carousel-cell"> <img src="{% static '/main/serach.png' %}" alt="">
          <div class="services_item">Search And Get Best Place According to Your Choice</div></div>
        <div class="carousel-cell"> <img src="{% static '/main/download.jpg' %}" alt="">
          <div class="services_item">Book Online Your Choice From Anywhere</div></div>
        <div class="carousel-cell"> <img src="{% static '/main/cppar.jpg' %}" alt="">
          <div class="services_item">Compare Our Site With The Others</div></div>
        
        
        
   </div>

</section>


<!-- Footer Section -->

<div class="footer ">
  <footer>
      <div class="footer-basic ">
          <div class="social ">
              <br>
              <a href="https://www.instagram.com/cloudcounselage/ "><i class="icon ion-social-instagram"></i></a>
              <a href="https://twitter.com/CloudCounselage "><i class="icon ion-social-twitter"></i></a>
              <a href="https://www.facebook.com/CloudCounselage/ "><i class="icon ion-social-facebook"></i></a></div>
          <ul class="list-inline ">
              <li class="list-inline-item "><a href="# ">Home</a></li>
              <li class="list-inline-item "><a href="#">Services</a></li>
              <li class="list-inline-item "><a href="#">About</a></li>
              <li class="list-inline-item "><a>Privacy Policy</a></li>
              <br><br>
          </ul>
          <p class="copyright ">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod, magnam distinctio id odit soluta fuga<br> consequatur officiis voluptatem architecto ab enim dicta, et natus ut cumque cum reiciendis repudiandae fugiat.<br><br></p>
      </div>
</div>
</footer>
</div>

<a href="main/contact"><img class ="contact" src="{% static '/main/contact.jpg' %}" alt="cintact image"></a>

{% endblock %}


{% block js %}
<script>
$(".more").click(function(){
  $(".more").hide();
  $(".hidden").show();

});

</script>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
{% endblock %}

biddu/main/templates/main/login.html
{% extends 'main/index.html' %} {% block title%} Login Page{% endblock%} {% block content%}
<div style="border: 1px solid black; margin: 110px 460px; width: 400px; height: 400px;  padding: 24px;"> 
    <h1 style="text-align:center;">Login</h1>
<br>
    <form action="{% url 'app:index' %}" method="post">
        {% csrf_token %} {{login_form.as_p}}<br>
        <input style="text-align: center;  padding: 7px; margin-left: 160px; line-height: 16px;font-size: 20px;border: 1px solid black; padding:4px 14px;font-weight: 300px;" type="submit" value="Login">
    </form>
    {{login_error}}
</div>
{% endblock%}

biddu/main/templates/main/register.html
{% extends 'main/index.html' %} {% block title%} Register Page{% endblock%} {% block content%}
<div style="border: 1px solid black; margin: 16px 260px; width: 700px; height: 560px; line-height: 39px; padding: 24px;"> 
<h1 style="text-align:center;">Register</h1>
<br>
    <form action="{% url 'userapp:index' %}" method="post"> {% csrf_token %} {{user_form.as_p}} {{user_info_form.as_p}}
       <br><input style="text-align: center;  padding: 7px; margin-left: 260px; line-height: 16px;font-size: 20px;border: 1px solid black; padding:4px 14px;font-weight: 300px;" type="submit" value="Register">
    </form>

</div>
{% endblock%}

biddu/main/templates/main/trial.html
@media only screen and (min-width: 1051px) {
  
  .form{
    margin-top: 100px;

  }
 

}
  

  @media only screen and (min-width: 1050px) and (max-width: 1214px)  {

    .form{
    margin-top: 50px;

  }
    
     
    .size{
      font-size: small;
    }

    
    }

    @media only screen and (min-width:670px) and  (max-width: 1050px){
    
    .search{
      grid-template-columns: repeat(2,1fr);
      display: grid;
      grid-gap:2px;
    }

    .destination{
    width: auto;   
}
 .type_of_residency {
    width: auto;
}

.type_of_room {
    width: auto;
}

.price-range
{ 
    font-size:inherit;
    width: auto;

}

.gender
{
    width: auto;
   
}



.search_btn{
  width: auto;
  
} 

    }

    @media screen  and (min-width: 992px){

      .form{
    margin-top: 20px;

  }

      .sign{
      position: absolute;
    right: 10px;
      }

      .log{
      position: absolute;
    right: 80px;
      }
      
    }

    @media only screen and (max-width: 670px)  {

      .form{
    margin-top: 20px;

  }


.search{
display: flex;
flex-direction: column;

}

.destination{
width: 100%;
margin: 2px; 
text-align: center;
}

.type_of_residency {
width: 100%;
margin: 2px; 
text-align: center;
}

.type_of_room {
width: 100%;
text-align: center;
margin: 2px; 
}

.price-range
{ 
font-size: medium;
width: 100%;
margin: 2px; 
text-align: center;

}

.gender
{
text-align: center;
width: 100%;
margin: 2px; 

}

.search_btn{
width: 100%;
margin: 2px; 

} 



}   

    
 </style>

<body>
    
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="mx-3 navbar-brand" href="#">Biddu</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link mx-5" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-5" href="#">WatchList</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled mx-5" href="#">My Favorite</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled mx-5" href="#">Memes</a>
          </li>

          <li class="nav-item">
            <a class="nav-link mx-5" href="#">Help</a>
          </li>
          <li class="nav-item log" >
            <a class="nav-link" href="{% url 'app:login' %}">Log-In</a>
          </li>
          <li class="nav-item sign">
            <a class="nav-link" href="{% url 'app:register' %}">Sign-Up</a>
          </li>
          
        </ul>

      </div>
    
    </nav>
    

    
        <form action="/action_page.php"class="form" >    
          <div class="search">
         
          <input class="destination size" type="text" placeholder="Search City.." name="search">
          
          <select class ="type_of_residency size" id="type_of_residency" name="type_of_residency">
            <option value="#" style="background-color: #e9e9e9;">Type of Residency</option>
            <option value="rent" class="drop-down-option">Rent</option>
            <option value="room" class="drop-down-option">Room</option>
            <option value="flat" class="drop-down-option">Flat</option>
            <option value="pg" class="drop-down-option">PG</option>
        </select>
        

          <select class ="size type_of_room" id="type_of_room" name="type_of_room">
            <option style="background-color: #e9e9e9;"value="#">Type of Room</option>
            <option value="rent" class="drop-down-option">Single Room</option>
            <option value="room" class="drop-down-option">Double Room</option>
            <option value="flat" class="drop-down-option">BHK</option>
          </select>

          
            <span class="price-range">
            <label for="vol">Select Budget:</label>
            <input type="range" id="vol" name="vol" min="0" max="100000">
            </span>

            <select class ="size gender" id="gender" name="gender">
              <option style="background-color: #e9e9e9;" value="#">For: </option>
              <option value="boys" class="drop-down-option">Boys</option>
              <option value="girls" class="drop-down-option">Girls</option>
              <option value="common" class="drop-down-option">Common</option>
            </select>
  
            <button class="search_btn" type="submit"><i class="fa fa-search"></i> Search</button>
            </div>
         
        </form>
        {% block content %} {% endblock %}
        <section class="about">
            <h3>About Book My PG</h3>
          <div class="visible">
            <p>
              Hi Student i'm your biddu ;) (biddu means friend) 
                  i'm here to help you to find your essential needs like rental rooms/pg's/mess etc.
                  In a location which gonna be selected by you.
                  You just tell me your needs and i will show you best results accordingly.
            </p>
          </div>
          <div class="more">Read More</div>
          <div class="hidden" style="display: none;">
              Get to know us

                  How Biddu comes from thought to the physical world ;

                  “Necessity is the mother of invention”
                  Similarly when we moved to a completely new city, there were a lot of things which seemed to be a very difficult task. If you are a student then these difficulties are doubled.

                  And one of these tasks is to find suitable and affordable accommodation.

                  Just think about the process of finding a room/PG/rented flat walking hours for 2-3 days without any direction,roaming in streets searching “TO LET” hoardings on gates and after checking 30-35 rooms you find a room.

                  Now think of a channel which connects you to the PGs and rooms;
                  - according to your needs,
                  -in your selected area,
                  -within your budget,
                  -without any physical work.

                  Now which way would you prefer?
                  Of Course the second wala…… 


                  So, @biddu.com we provide that channel to you..
                  Our mission is to cut off the tiredy task of finding you rooms from ground to phones and PCs .

                  NOW shift to new place TENSION FREE.
            </div>
          
        </section>

        <section class="services">
          <h1>Our Services</h1>
          <div class="carousel"
                data-flickity='{ "wrapAround": true }'>
                <div class="carousel-cell"> <img src="{% static '/main/serach.png' %}" alt="">
                  <div class="services_item">Search And Get Best Place According to Your Choice</div></div>
                <div class="carousel-cell"> <img src="{% static '/main/download.jpg' %}" alt="">
                  <div class="services_item">Book Online Your Choice From Anywhere</div></div>
                <div class="carousel-cell"> <img src="{% static '/main/cppar.jpg' %}" alt="">
                  <div class="services_item">Compare Our Site With The Others</div></div>
                
                
                
           </div>

        </section>
<!-- 
        <div class='popup'>
          <div class='cnt223'>
           <h1>Move on into Admin Panel</h1>
           <p>
          If You are an Admin, Move into Admin Panal...
           </p>
          <button class='close'>Close</button>
          
          </div>
        </div> -->
      

        <!-- Footer Section -->

        <div class="footer ">
          <footer>
              <div class="footer-basic ">
                  <div class="social ">
                      <br>
                      <a href="https://www.instagram.com/cloudcounselage/ "><i class="icon ion-social-instagram"></i></a>
                      <a href="https://twitter.com/CloudCounselage "><i class="icon ion-social-twitter"></i></a>
                      <a href="https://www.facebook.com/CloudCounselage/ "><i class="icon ion-social-facebook"></i></a></div>
                  <ul class="list-inline ">
                      <li class="list-inline-item "><a href="# ">Home</a></li>
                      <li class="list-inline-item "><a href="#">Services</a></li>
                      <li class="list-inline-item "><a href="#">About</a></li>
                      <li class="list-inline-item "><a>Privacy Policy</a></li>
                      <br><br>
                  </ul>
                  
              </div>
      </div>
      </footer>
      </div>

      <a href=""><img class ="contact" src="{% static '/main/contact.jpg' %}" alt="cintact image"></a>
</body>

<!-- <script type="text/javascript" src="https://code.jquery.com/jquery-1.8.2.js"></script>

<script type='text/javascript'>
  $(function(){

  $('.popup').show();
  $('.close').click(function(){
  $('.popup').hide();
  return false;
  });
});

  </script> -->


<!-- bootstrap -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>

{% block js %}
<script>
  $(".more").click(function(){
  $(".more").hide();
  $(".hidden").show();

});


</script>
{% endblock %}

<!-- Pop Up form -->


</html>